#!/usr/bin/env bun
/**
 * Build script for interago.exe
 *
 * yoga-wasm-web/auto on Node/Bun resolves to dist/node.js which uses
 * createRequire().resolve() + readFile() to load yoga.wasm at runtime.
 * Inside Bun's compiled binary that path doesn't exist on disk, so it fails.
 *
 * Fix: redirect ./auto to a thin wrapper that calls the pure-JS asm factory
 * (dist/asm.js) synchronously — no WASM file needed.
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { $ } from "bun";

const root = join(import.meta.dir, "..");
process.chdir(root);
const yogaDir = join(root, "node_modules/yoga-wasm-web");
const yogaDist = join(yogaDir, "dist");
const yogaPkgPath = join(yogaDir, "package.json");

// 1. Write the asm wrapper (pure-JS, no WASM loading)
const asmWrapperPath = join(yogaDist, "asm-wrapper.js");
const asmWrapperSrc =
  [
    "// Auto-generated by build.ts — pure-JS yoga, no WASM",
    "import asmFactory from './asm.js';",
    "export * from './asm.js';",
    "const Yoga = asmFactory();",
    "export { Yoga as default };",
  ].join("\n") + "\n";

writeFileSync(asmWrapperPath, asmWrapperSrc, "utf8");

// 2. Patch yoga-wasm-web package.json to redirect ./auto → asm-wrapper
const yogaPkg = JSON.parse(readFileSync(yogaPkgPath, "utf8"));
const originalAutoDefault = yogaPkg.exports["./auto"].default;
yogaPkg.exports["./auto"].default = "./dist/asm-wrapper.js";
writeFileSync(yogaPkgPath, JSON.stringify(yogaPkg, null, 2), "utf8");
console.log("Patched yoga-wasm-web/auto → asm-wrapper (no WASM)");

try {
  // 3. Compile
  await $`bun build --windows-icon=./src/assets/icon.ico --compile ./src/index.tsx --outfile interago`;
  console.log("Build complete: interago.exe");
} finally {
  // 4. Restore original package.json
  yogaPkg.exports["./auto"].default = originalAutoDefault;
  writeFileSync(yogaPkgPath, JSON.stringify(yogaPkg, null, 2), "utf8");
  console.log("Restored yoga-wasm-web/package.json");
}
